# Generated by Django 5.0.6 on 2024-06-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggenerator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='input',
        ),
    ]
